# -*- coding: utf-8 -*-
import os
import google.generativeai as genai
from flask import Flask, request, render_template_string
from dotenv import load_dotenv

# --- CONFIGURATION ---
load_dotenv()
app = Flask(__name__)

# Configure Gemini API
api_key = os.environ.get("GOOGLE_API_KEY")

if api_key:
    genai.configure(api_key=api_key)

# --- AVA SYSTEM PROMPT ---
def get_ava_prompt(user_raw_input):
    return f"""
    You are **Ava**, a senior real-estate copywriter created by **AgentCoachAI**.
    You write persuasive, cinematic, and Fair-Housing-compliant property descriptions.

    OBJECTIVE: Take the raw property details provided below and immediately generate the three required descriptions. 
    
    CRITICAL RULES: 
    1. DO NOT converse with the user.
    2. DO NOT ask for more information. 
    3. If the input is very short, use your creative copywriting skills to expand, embellish, and paint a picture of the provided features (like "new kitchen") to reach the required word counts. Just output the three descriptions.
    4. OUTPUT LANGUAGE: ENGLISH ONLY.

    OUTPUT FORMAT (Do not include introductory text, just the three versions):
    
    ### 1. Cinematic / Luxury Version
    (400–600 words. Vivid, sensory details, storytelling structure.)

    ### 2. Professional / Neutral Version
    (300–450 words. MLS-ready, factual, focuses on features and proximity.)

    ### 3. Short Summary Version
    (120–200 words. Concise teaser, best 3-4 selling points.)

    COMPLIANCE: No Fair-Housing violations.
    ENDING REQUIREMENT: Always end the final output with exactly: "Description generated by Ava — AgentCoachAI. FH-Compliant."

    ====================
    RAW PROPERTY DETAILS PROVIDED BY USER:
    ====================
    {user_raw_input}
    """

# --- FRONTEND (CON INDICADOR DE CARGA) ---
HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ava - Agent Coach AI</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
    <style>
        :root {
            --bg-color: #121212;
            --chat-bg: #1E1E1E;
            --text-color: #E0E0E0;
            --accent-color: #7C4DFF;
            --input-bg: #2C2C2C;
        }
        body { font-family: 'Inter', sans-serif; background-color: var(--bg-color); color: var(--text-color); margin: 0; display: flex; flex-direction: column; height: 100vh; }
        
        .header { padding: 20px; text-align: center; border-bottom: 1px solid #333; }
        .header h1 { margin: 0; font-size: 1.5rem; display: flex; align-items: center; justify-content: center; gap: 10px; }
        .header span { font-size: 0.9rem; color: #888; display: block; margin-top: 5px; }

        .chat-container { flex: 1; overflow-y: auto; padding: 20px; display: flex; flex-direction: column; gap: 20px; max-width: 900px; margin: 0 auto; width: 100%; box-sizing: border-box; }
        
        .message { display: flex; gap: 15px; max-width: 85%; animation: fadeIn 0.3s ease-in; }
        .bot-avatar { width: 40px; height: 40px; background-color: var(--accent-color); border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: bold; flex-shrink: 0;}
        .message-content { background-color: var(--chat-bg); padding: 15px 20px; border-radius: 12px; line-height: 1.6; white-space: pre-wrap; }
        
        /* Loading Spinner */
        .loading-dots { display: none; padding: 10px; font-style: italic; color: #888; }
        .loading-dots:after { content: ' .'; animation: dots 1.5s steps(5, end) infinite;}
        @keyframes dots { 0%, 20% { color: rgba(0,0,0,0); text-shadow: .25em 0 0 rgba(0,0,0,0), .5em 0 0 rgba(0,0,0,0); } 40% { color: #888; text-shadow: .25em 0 0 rgba(0,0,0,0), .5em 0 0 rgba(0,0,0,0); } 60% { text-shadow: .25em 0 0 #888, .5em 0 0 rgba(0,0,0,0); } 80%, 100% { text-shadow: .25em 0 0 #888, .5em 0 0 #888; } }

        .input-area { padding: 20px; background-color: var(--bg-color); border-top: 1px solid #333; }
        .input-form { max-width: 900px; margin: 0 auto; position: relative; display: flex; }
        textarea { width: 100%; background-color: var(--input-bg); border: 1px solid #444; border-radius: 25px; color: white; padding: 15px 50px 15px 20px; resize: none; height: 60px; font-family: inherit; outline: none; }
        textarea:disabled { opacity: 0.5; }
        .send-btn { position: absolute; right: 10px; top: 50%; transform: translateY(-50%); background: transparent; border: none; color: var(--accent-color); font-size: 24px; cursor: pointer; padding: 5px 10px; }
        
        .error-box { background-color: #cf6679; color: white; padding: 15px; border-radius: 8px; margin-bottom: 20px; text-align: center;}
        @keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }
        h3 { color: var(--accent-color); margin-top: 25px; margin-bottom: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>🚀 Ava — Real Estate Copywriter</h1>
        <span>Powered by Agent Coach AI</span>
    </div>

    <div class="chat-container" id="chat-container">
        <div class="message bot-message">
            <div class="bot-avatar">A</div>
            <div class="message-content">Hi, I'm <strong>Ava</strong>. Type the property details below to start.</div>
        </div>

        {% if error %}
        <div class="error-box">⚠️ {{ error }}</div>
        {% endif %}

        {% if generated_text %}
        <div class="message bot-message">
            <div class="bot-avatar">A</div>
            <div class="message-content">{{ generated_text }}</div>
        </div>
        {% endif %}

        <div id="loading" class="message bot-message" style="display:none;">
            <div class="bot-avatar">A</div>
            <div class="message-content"><span class="loading-dots">Ava is thinking</span></div>
        </div>
    </div>

    <div class="input-area">
        <form class="input-form" id="ava-form" method="POST" action="/">
            <textarea name="user_input" id="user_input" placeholder="Type property details here..." required></textarea>
            <button type="submit" class="send-btn" id="send-btn">➤</button>
        </form>
    </div>

    <script>
        const form = document.getElementById('ava-form');
        const loading = document.getElementById('loading');
        const chatContainer = document.getElementById('chat-container');
        const userInput = document.getElementById('user_input');
        const sendBtn = document.getElementById('send-btn');

        // Auto-scroll al final
        chatContainer.scrollTop = chatContainer.scrollHeight;

        form.onsubmit = function() {
            loading.style.display = 'flex';
            userInput.disabled = true;
            sendBtn.style.display = 'none';
            chatContainer.scrollTop = chatContainer.scrollHeight;
        };

        userInput.addEventListener('keydown', function(e) {
            if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                if(this.value.trim() !== "") form.submit();
            }
        });
    </script>
</body>
</html>
""" 

# --- ROUTES ---
@app.route("/", methods=["GET", "POST"])
def home():
    generated_text = ""
    error_message = ""
    
    if request.method == "POST":
        if not api_key:
            error_message = "Error: Google API Key missing."
        else:
            try:
                user_input_block = request.form.get("user_input")
                
                # CORRECCIÓN DE MODELO: 'gemini-2.0-flash' es el nombre correcto actual. 
                # Si quieres estabilidad total usa 'gemini-1.5-flash'
                model = genai.GenerativeModel('gemini-2.5-flash')
                
                response = model.generate_content(get_ava_prompt(user_input_block))
                generated_text = response.text
                
            except Exception as e:
                error_message = f"Connection error: {str(e)}"

    return render_template_string(HTML_TEMPLATE, generated_text=generated_text, error=error_message)

if __name__ == "__main__":
    app.run(debug=True)
