# -*- coding: utf-8 -*-
import os
import google.generativeai as genai
from flask import Flask, request, render_template_string
from dotenv import load_dotenv

# --- CONFIGURATION ---
load_dotenv()
app = Flask(__name__)

# Configure Gemini API
api_key = os.environ.get("GOOGLE_API_KEY")

if api_key:
    genai.configure(api_key=api_key)

# --- AVA SYSTEM PROMPT ---
def get_ava_prompt(user_inputs):
    return f"""
    You are Ava, a senior real-estate copywriter created by AgentCoachAI.
    You write persuasive, cinematic, and Fair-Housing-compliant property descriptions.

    OBJECTIVE: Turn raw details into market-ready stories.
    CRITICAL: OUTPUT LANGUAGE: ENGLISH ONLY.

    OUTPUT FORMAT:
    1. Cinematic / Luxury Version (400-600 words)
    2. Professional / Neutral Version (300-450 words)
    3. Short Summary Version (120-200 words)

    STYLE: Professional, tangible details, factual but inspiring.
    COMPLIANCE: No Fair-Housing violations.
    ENDING: "Description generated by Ava - AgentCoachAI. FH-Compliant."

    PROPERTY DETAILS:
    {user_inputs}
    """

# --- FRONTEND (HTML/CSS) ---
# AQUI ES DONDE OCURRIA EL ERROR. NO BORRES LAS 3 COMILLAS DE ABAJO:
HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ava - Real Estate Copywriter</title>
    <style>
        body { font-family: sans-serif; background-color: #f4f6f8; color: #333; padding: 20px; }
        .container { max-width: 800px; margin: 0 auto; background: white; padding: 40px; border-radius: 8px; }
        h1 { text-align: center; color: #1a202c; }
        label { display: block; margin-top: 15px; font-weight: bold; }
        input, textarea { width: 100%; padding: 10px; margin-top: 5px; border: 1px solid #ddd; border-radius: 4px; box-sizing: border-box; }
        button { background-color: #3182ce; color: white; padding: 15px; border: none; border-radius: 4px; width: 100%; margin-top: 20px; cursor: pointer; font-size: 16px; }
        button:hover { background-color: #2b6cb0; }
        .result-box { background: #f7fafc; padding: 20px; border-radius: 4px; margin-top: 30px; border: 1px solid #e2e8f0; white-space: pre-wrap; line-height: 1.6; }
        .error { color: red; text-align: center; margin-top: 10px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Ava: Real Estate AI</h1>
        <form method="POST" action="/">
            <label>Property Address</label>
            <input type="text" name="address" required>
            
            <label>Home Type</label>
            <input type="text" name="home_type">
            
            <label>Specs (Beds, Baths, SqFt)</label>
            <input type="text" name="specs" required>
            
            <label>Neighborhood Highlights</label>
            <textarea name="neighborhood"></textarea>
            
            <label>Key Features</label>
            <textarea name="features" required></textarea>
            
            <button type="submit">Generate Descriptions</button>
        </form>

        {% if generated_text %}
        <div class="result-box">
            <h3>Generated Listings:</h3>
            {{ generated_text }}
        </div>
        {% endif %}
        
        {% if error %}
        <div class="error">{{ error }}</div>
        {% endif %}
    </div>
</body>
</html>
""" 
# --- FIN DEL HTML ---

# --- ROUTES ---
@app.route("/", methods=["GET", "POST"])
def home():
    generated_text = ""
    error_message = ""
    
    if request.method == "POST":
        if not api_key:
            error_message = "Error: GOOGLE_API_KEY not found in variables."
        else:
            try:
                address = request.form.get("address")
                home_type = request.form.get("home_type")
                specs = request.form.get("specs")
                neighborhood = request.form.get("neighborhood")
                features = request.form.get("features")
                
                user_data = f"Address: {address}, Type: {home_type}, Specs: {specs}, Neighborhood: {neighborhood}, Features: {features}"
                
                model = genai.GenerativeModel('gemini-1.5-flash')
                response = model.generate_content(get_ava_prompt(user_data))
                generated_text = response.text
            except Exception as e:
                error_message = str(e)

    return render_template_string(HTML_TEMPLATE, generated_text=generated_text, error=error_message)

if __name__ == "__main__":
    app.run(debug=True)
